project:
  type: book
  output-dir: docs

book:
  title: "Yigit Onay Progress Journal"
  repo-url: https://github.com/pjournal/mef06-yigitonay
  chapters:
    - index.qmd
    - assignment1.qmd
    - In_class_Assignment.qmd
    - shiny.qmd
    - or_case_study.qmd
  page-footer: 
    center: "[MEF BDA 503](https://mef-bda503.github.io)" 
  sharing: [twitter, facebook]

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

