project:
  type: book
  output-dir: docs

book:
  title: "[STUDENT/GROUP NAME] Progress Journal"
  repo-url: https://github.com/pjournal/gh-pages-quarto-template
  chapters:
    - index.qmd
    - assignment1.qmd
  page-footer: 
    center: "[MEF BDA 503](https://mef-bda503.github.io)" 
  sharing: [twitter, facebook]

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

